import { Noto_Sans } from 'next/font/google';
import type { Metadata } from 'next';
import '@/styles/reset.css';

const noto = Noto_Sans({ display: 'auto', subsets: ['latin'], variable: '--font-noto-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// 글로벌 변수에 폰트 변수 적용 완료
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className={noto.variable}>
      <body>{children}</body>
    </html>
  );
}
